lora_modules:
- base_model: qwen2.5-32b-awq
  name: to-activate
  path: /private/var/folders/55/8tvvy84112342fvgn__327180000gn/T/pytest-of-julian/pytest-129/test_activate_adapter0/to-activate
models:
- gpus:
  - 0
  id: qwen2.5-32b-awq
  mode: replica
strategy: replica
